name = "fred-agente-de-proposta"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".open-next/assets", binding = "ASSETS" }

[[d1_databases]]
binding = "DB"
database_name = "v4-delivery-db"
database_id = "545a9890-9ae5-4c9e-9058-4f4f7a4d305e"
